version: "2"

services:
  firstapp:
    build: ./
    working_dir: /var/www/html/public
    container_name: firstapp
    restart: always
    volumes:
      - ../public:/var/www/html/public
    ports:
      - "8091:80"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sevo
      MYSQL_USER: sevo_user
      MYSQL_PASSWORD: 111111