<div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="/">Anasayfa</a>
        </li>
        <li class="breadcrumb-item">
            <a href="/user/index">Kullanıcılar</a>
        </li>
        <li class="breadcrumb-item active">Kullanıcı Ekle</li>
    </ol>


    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i> Kullanıcı Ekle
        </div>
        <div class="card-body">

            <!--içerik buraya gelecek-->
            <form action="" method="post">
                <div class="row justify-content-md-center">
                    <div class="col-md-4">

                        <div class="form-group">
                            <label for="exampleInputPassword1">Kullanıcı Adı:</label>
                            <input type="text" name="user_name" class="form-control" id="exampleInputPassword1"
                                   placeholder="kullanıcı adı" value="">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">E-posta:</label>
                            <input type="email" name="email" class="form-control" id="exampleInputEmail1"
                                   aria-describedby="emailHelp" placeholder="e-posta" value="">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Şifre:</label>
                            <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                                   placeholder="şifre" value="">
                        </div>

                        <button type="submit" name="gonder" class="btn btn-primary">Ekle</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>