<div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Kullanıcılar</a>
        </li>
        <li class="breadcrumb-item active">Liste</li>
    </ol>


    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i> Kullanıcılar
        </div>
        <div class="card-body">

            <!--içerik buraya gelecek-->
            Şevval

        </div>
    </div>
</div>